# Generated by Django 3.1.13 on 2022-02-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_auto_20220214_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('lyric', models.TextField()),
                ('rank', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
