# Generated by Django 3.1.13 on 2022-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_auto_20220215_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='image',
            field=models.ImageField(default='img', upload_to='img'),
            preserve_default=False,
        ),
    ]
