# Generated by Django 3.1.13 on 2022-02-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0005_auto_20220218_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyricinsert',
            old_name='lyric',
            new_name='lyric_candidate',
        ),
    ]
